#This is a script for ResNet50
#ResNet50 :  module/model/resblock_repeat = [3, 4, 6, 3]

# traces / csv / age_col로 수정
data:
  folder: model_hx/
  score_col: score_H2FPEF
  whole : ./ecgmaster-echo_365_shape.csv
  trace_dir : ../../ecg-echo/220927_SevMUSE_EKG_waveform/
  
setup:
  phase: train
  num_models: 1
  epochs: 100
  earlystop : 15
  batch_size: 512
  seed: 626
  sample_freq: 500
  seq_length: 5000
  num_workers : 4
  ec2: g4dn.8xlarge

module:
  model:
    name: RNN15
    model_name: 230129_RNN15
    data_parallel : False
    dropout_rate: 0.5
    net_filter_size: [64, 128, 196, 256, 320] #[256, 512, 1024, 2048] #resnet50/101/152 
    net_seq_length: [5000, 1000, 200, 40, 8] #[5120, 1280, 320, 80, 20]
    kernel_size: 17

  optim: 
    name: Adam
    lr: 0.001
    patience: 7
    min_lr: 0.0000001
    lr_factor: 0.1
    lr_scheduler: ReduceLROnPlateau

  loss: MSE
  code: CUDA_VISIBLE_DEVICES=3 python train.py script
